//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class attachements
    {
        public int attachement_id { get; set; }
        public string filename { get; set; }
        public string bezeichnung { get; set; }
        public Nullable<int> size { get; set; }
        public string mimetype { get; set; }
        public Nullable<int> hauspaket_id { get; set; }
    }
}
