//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hauspaket_attribut_wert
    {
        public int wert_id { get; set; }
        public Nullable<int> attribut_id { get; set; }
        public string wert_text { get; set; }
        public Nullable<int> wert_ordnung { get; set; }
        public Nullable<bool> archived { get; set; }
    }
}
