//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hauspaket_attribut_zuord
    {
        public int hauspaket_id { get; set; }
        public int wert_id { get; set; }
    }
}
