//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hauspaket
    {
        public int hauspaket_id { get; set; }
        public Nullable<int> hersteller_id { get; set; }
        public Nullable<int> berater_id { get; set; }
        public string bezeichnung { get; set; }
        public Nullable<decimal> preis { get; set; }
        public Nullable<decimal> grundflaeche { get; set; }
        public Nullable<decimal> wohnflaeche { get; set; }
        public Nullable<int> stockwerke { get; set; }
        public Nullable<int> benutzer_id { get; set; }
        public Nullable<bool> archived { get; set; }
    }
}
