//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hauspaket_attribut
    {
        public int attribut_id { get; set; }
        public string attribut_typ { get; set; }
        public string attribut_typ_anzeige { get; set; }
    }
}
