//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class hauspaket_attribut_regel
    {
        public int regel_id { get; set; }
        public Nullable<int> regel_attribut_left_id { get; set; }
        public Nullable<int> regel_attribut_right_id { get; set; }
        public Nullable<decimal> regel_preis_modifikator { get; set; }
        public Nullable<bool> regel_erlaubt { get; set; }
    }
}
