//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalDbEntities : DbContext
    {
        public LocalDbEntities()
            : base("name=LocalDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attachements> attachements { get; set; }
        public virtual DbSet<berater> berater { get; set; }
        public virtual DbSet<hauspaket> hauspaket { get; set; }
        public virtual DbSet<hauspaket_attribut> hauspaket_attribut { get; set; }
        public virtual DbSet<hauspaket_attribut_regel> hauspaket_attribut_regel { get; set; }
        public virtual DbSet<hauspaket_attribut_wert> hauspaket_attribut_wert { get; set; }
        public virtual DbSet<hauspaket_attribut_zuord> hauspaket_attribut_zuord { get; set; }
        public virtual DbSet<hersteller> hersteller { get; set; }
        public virtual DbSet<sync_jn> sync_jn { get; set; }
    }
}
