//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sync_jn
    {
        public int jn_id { get; set; }
        public string jn_table { get; set; }
        public Nullable<System.DateTime> jn_timestampe { get; set; }
        public Nullable<int> jn_pk { get; set; }
        public string jn_operation { get; set; }
        public Nullable<bool> jn_synced { get; set; }
        public string jn_changeset_json { get; set; }
    }
}
