//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchronisationDataManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sync_jn
    {
        public int jn_id { get; set; }
        public string jn_table { get; set; }
        public byte[] jn_timestamp { get; set; }
        public int jn_pk { get; set; }
        public string jn_operation { get; set; }
        public byte jn_synced { get; set; }
        public string jn_changeset_json { get; set; }
        public string jn_application { get; set; }
    }
}
