//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchronisationLib.SynchronisationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyncData", Namespace="http://schemas.datacontract.org/2004/07/SynchronisationShared")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.Table))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.Attachements))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.HauspaketAttributZuord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.Berater))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.HauspaketAttributRegel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.HauspaketAttribut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.HauspaketAttributWert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.Hauspaket))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.Hersteller))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.HauspaketDTO))]
    public partial class SyncData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SyncOperationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SyncOperation {
            get {
                return this.SyncOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.SyncOperationField, value) != true)) {
                    this.SyncOperationField = value;
                    this.RaisePropertyChanged("SyncOperation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Table", Namespace="http://schemas.datacontract.org/2004/07/SynchronisationDataManager.Tables")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.Attachements))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.HauspaketAttributZuord))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.Berater))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.HauspaketAttributRegel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.HauspaketAttribut))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.HauspaketAttributWert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.Hauspaket))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SynchronisationLib.SynchronisationService.Hersteller))]
    public partial class Table : SynchronisationLib.SynchronisationService.SyncData {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attachements", Namespace="http://schemas.datacontract.org/2004/07/SynchronisationDataManager.Tables")]
    [System.SerializableAttribute()]
    public partial class Attachements : SynchronisationLib.SynchronisationService.Table {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AttachementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BezeichnungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HauspaketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MimetypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AttachementId {
            get {
                return this.AttachementIdField;
            }
            set {
                if ((this.AttachementIdField.Equals(value) != true)) {
                    this.AttachementIdField = value;
                    this.RaisePropertyChanged("AttachementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bezeichnung {
            get {
                return this.BezeichnungField;
            }
            set {
                if ((object.ReferenceEquals(this.BezeichnungField, value) != true)) {
                    this.BezeichnungField = value;
                    this.RaisePropertyChanged("Bezeichnung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename {
            get {
                return this.FilenameField;
            }
            set {
                if ((object.ReferenceEquals(this.FilenameField, value) != true)) {
                    this.FilenameField = value;
                    this.RaisePropertyChanged("Filename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HauspaketId {
            get {
                return this.HauspaketIdField;
            }
            set {
                if ((this.HauspaketIdField.Equals(value) != true)) {
                    this.HauspaketIdField = value;
                    this.RaisePropertyChanged("HauspaketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mimetype {
            get {
                return this.MimetypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MimetypeField, value) != true)) {
                    this.MimetypeField = value;
                    this.RaisePropertyChanged("Mimetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Size {
            get {
                return this.SizeField;
            }
            set {
                if ((this.SizeField.Equals(value) != true)) {
                    this.SizeField = value;
                    this.RaisePropertyChanged("Size");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HauspaketAttributZuord", Namespace="http://schemas.datacontract.org/2004/07/SynchronisationDataManager.Tables")]
    [System.SerializableAttribute()]
    public partial class HauspaketAttributZuord : SynchronisationLib.SynchronisationService.Table {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HauspaketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WertIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HauspaketId {
            get {
                return this.HauspaketIdField;
            }
            set {
                if ((this.HauspaketIdField.Equals(value) != true)) {
                    this.HauspaketIdField = value;
                    this.RaisePropertyChanged("HauspaketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WertId {
            get {
                return this.WertIdField;
            }
            set {
                if ((this.WertIdField.Equals(value) != true)) {
                    this.WertIdField = value;
                    this.RaisePropertyChanged("WertId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Berater", Namespace="http://schemas.datacontract.org/2004/07/SynchronisationDataManager.Tables")]
    [System.SerializableAttribute()]
    public partial class Berater : SynchronisationLib.SynchronisationService.Table {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BenutzerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BeraterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BildField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HerstellerIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BenutzerId {
            get {
                return this.BenutzerIdField;
            }
            set {
                if ((this.BenutzerIdField.Equals(value) != true)) {
                    this.BenutzerIdField = value;
                    this.RaisePropertyChanged("BenutzerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BeraterId {
            get {
                return this.BeraterIdField;
            }
            set {
                if ((this.BeraterIdField.Equals(value) != true)) {
                    this.BeraterIdField = value;
                    this.RaisePropertyChanged("BeraterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bild {
            get {
                return this.BildField;
            }
            set {
                if ((object.ReferenceEquals(this.BildField, value) != true)) {
                    this.BildField = value;
                    this.RaisePropertyChanged("Bild");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HerstellerId {
            get {
                return this.HerstellerIdField;
            }
            set {
                if ((this.HerstellerIdField.Equals(value) != true)) {
                    this.HerstellerIdField = value;
                    this.RaisePropertyChanged("HerstellerId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HauspaketAttributRegel", Namespace="http://schemas.datacontract.org/2004/07/SynchronisationDataManager.Tables")]
    [System.SerializableAttribute()]
    public partial class HauspaketAttributRegel : SynchronisationLib.SynchronisationService.Table {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RegelAttributLeftIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RegelAttributRightIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegelErlaubtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RegelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> RegelPreisModifikatorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RegelAttributLeftId {
            get {
                return this.RegelAttributLeftIdField;
            }
            set {
                if ((this.RegelAttributLeftIdField.Equals(value) != true)) {
                    this.RegelAttributLeftIdField = value;
                    this.RaisePropertyChanged("RegelAttributLeftId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RegelAttributRightId {
            get {
                return this.RegelAttributRightIdField;
            }
            set {
                if ((this.RegelAttributRightIdField.Equals(value) != true)) {
                    this.RegelAttributRightIdField = value;
                    this.RaisePropertyChanged("RegelAttributRightId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegelErlaubt {
            get {
                return this.RegelErlaubtField;
            }
            set {
                if ((object.ReferenceEquals(this.RegelErlaubtField, value) != true)) {
                    this.RegelErlaubtField = value;
                    this.RaisePropertyChanged("RegelErlaubt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RegelId {
            get {
                return this.RegelIdField;
            }
            set {
                if ((this.RegelIdField.Equals(value) != true)) {
                    this.RegelIdField = value;
                    this.RaisePropertyChanged("RegelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> RegelPreisModifikator {
            get {
                return this.RegelPreisModifikatorField;
            }
            set {
                if ((this.RegelPreisModifikatorField.Equals(value) != true)) {
                    this.RegelPreisModifikatorField = value;
                    this.RaisePropertyChanged("RegelPreisModifikator");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HauspaketAttribut", Namespace="http://schemas.datacontract.org/2004/07/SynchronisationDataManager.Tables")]
    [System.SerializableAttribute()]
    public partial class HauspaketAttribut : SynchronisationLib.SynchronisationService.Table {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AttributIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributTypField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributTypAnzeigeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AttributId {
            get {
                return this.AttributIdField;
            }
            set {
                if ((this.AttributIdField.Equals(value) != true)) {
                    this.AttributIdField = value;
                    this.RaisePropertyChanged("AttributId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttributTyp {
            get {
                return this.AttributTypField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributTypField, value) != true)) {
                    this.AttributTypField = value;
                    this.RaisePropertyChanged("AttributTyp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttributTypAnzeige {
            get {
                return this.AttributTypAnzeigeField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributTypAnzeigeField, value) != true)) {
                    this.AttributTypAnzeigeField = value;
                    this.RaisePropertyChanged("AttributTypAnzeige");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HauspaketAttributWert", Namespace="http://schemas.datacontract.org/2004/07/SynchronisationDataManager.Tables")]
    [System.SerializableAttribute()]
    public partial class HauspaketAttributWert : SynchronisationLib.SynchronisationService.Table {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AttributIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WertIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WertOrdnungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WertTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archived {
            get {
                return this.ArchivedField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivedField, value) != true)) {
                    this.ArchivedField = value;
                    this.RaisePropertyChanged("Archived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AttributId {
            get {
                return this.AttributIdField;
            }
            set {
                if ((this.AttributIdField.Equals(value) != true)) {
                    this.AttributIdField = value;
                    this.RaisePropertyChanged("AttributId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WertId {
            get {
                return this.WertIdField;
            }
            set {
                if ((this.WertIdField.Equals(value) != true)) {
                    this.WertIdField = value;
                    this.RaisePropertyChanged("WertId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WertOrdnung {
            get {
                return this.WertOrdnungField;
            }
            set {
                if ((this.WertOrdnungField.Equals(value) != true)) {
                    this.WertOrdnungField = value;
                    this.RaisePropertyChanged("WertOrdnung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WertText {
            get {
                return this.WertTextField;
            }
            set {
                if ((object.ReferenceEquals(this.WertTextField, value) != true)) {
                    this.WertTextField = value;
                    this.RaisePropertyChanged("WertText");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hauspaket", Namespace="http://schemas.datacontract.org/2004/07/SynchronisationDataManager.Tables")]
    [System.SerializableAttribute()]
    public partial class Hauspaket : SynchronisationLib.SynchronisationService.Table {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BenutzerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BeraterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BezeichnungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> GrundflaecheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HauspaketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HerstellerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PreisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StockwerkeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> WohnflaecheField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archived {
            get {
                return this.ArchivedField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivedField, value) != true)) {
                    this.ArchivedField = value;
                    this.RaisePropertyChanged("Archived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BenutzerId {
            get {
                return this.BenutzerIdField;
            }
            set {
                if ((this.BenutzerIdField.Equals(value) != true)) {
                    this.BenutzerIdField = value;
                    this.RaisePropertyChanged("BenutzerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BeraterId {
            get {
                return this.BeraterIdField;
            }
            set {
                if ((this.BeraterIdField.Equals(value) != true)) {
                    this.BeraterIdField = value;
                    this.RaisePropertyChanged("BeraterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bezeichnung {
            get {
                return this.BezeichnungField;
            }
            set {
                if ((object.ReferenceEquals(this.BezeichnungField, value) != true)) {
                    this.BezeichnungField = value;
                    this.RaisePropertyChanged("Bezeichnung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Grundflaeche {
            get {
                return this.GrundflaecheField;
            }
            set {
                if ((this.GrundflaecheField.Equals(value) != true)) {
                    this.GrundflaecheField = value;
                    this.RaisePropertyChanged("Grundflaeche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HauspaketId {
            get {
                return this.HauspaketIdField;
            }
            set {
                if ((this.HauspaketIdField.Equals(value) != true)) {
                    this.HauspaketIdField = value;
                    this.RaisePropertyChanged("HauspaketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HerstellerId {
            get {
                return this.HerstellerIdField;
            }
            set {
                if ((this.HerstellerIdField.Equals(value) != true)) {
                    this.HerstellerIdField = value;
                    this.RaisePropertyChanged("HerstellerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Preis {
            get {
                return this.PreisField;
            }
            set {
                if ((this.PreisField.Equals(value) != true)) {
                    this.PreisField = value;
                    this.RaisePropertyChanged("Preis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Stockwerke {
            get {
                return this.StockwerkeField;
            }
            set {
                if ((this.StockwerkeField.Equals(value) != true)) {
                    this.StockwerkeField = value;
                    this.RaisePropertyChanged("Stockwerke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Wohnflaeche {
            get {
                return this.WohnflaecheField;
            }
            set {
                if ((this.WohnflaecheField.Equals(value) != true)) {
                    this.WohnflaecheField = value;
                    this.RaisePropertyChanged("Wohnflaeche");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hersteller", Namespace="http://schemas.datacontract.org/2004/07/SynchronisationDataManager.Tables")]
    [System.SerializableAttribute()]
    public partial class Hersteller : SynchronisationLib.SynchronisationService.Table {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HerstellerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HerstellerId {
            get {
                return this.HerstellerIdField;
            }
            set {
                if ((this.HerstellerIdField.Equals(value) != true)) {
                    this.HerstellerIdField = value;
                    this.RaisePropertyChanged("HerstellerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HauspaketDTO", Namespace="http://schemas.datacontract.org/2004/07/SynchronisationDataManager.Tables")]
    [System.SerializableAttribute()]
    public partial class HauspaketDTO : SynchronisationLib.SynchronisationService.SyncData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArchivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BenutzerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BeraterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BezeichnungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> GrundflaecheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronisationLib.SynchronisationService.Attachements> HauspaketAttachementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronisationLib.SynchronisationService.HauspaketAttributZuord> HauspaketAttributZuordnungenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HauspaketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HerstellerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> PreisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StockwerkeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> WohnflaecheField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Archived {
            get {
                return this.ArchivedField;
            }
            set {
                if ((object.ReferenceEquals(this.ArchivedField, value) != true)) {
                    this.ArchivedField = value;
                    this.RaisePropertyChanged("Archived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BenutzerId {
            get {
                return this.BenutzerIdField;
            }
            set {
                if ((this.BenutzerIdField.Equals(value) != true)) {
                    this.BenutzerIdField = value;
                    this.RaisePropertyChanged("BenutzerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BeraterId {
            get {
                return this.BeraterIdField;
            }
            set {
                if ((this.BeraterIdField.Equals(value) != true)) {
                    this.BeraterIdField = value;
                    this.RaisePropertyChanged("BeraterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bezeichnung {
            get {
                return this.BezeichnungField;
            }
            set {
                if ((object.ReferenceEquals(this.BezeichnungField, value) != true)) {
                    this.BezeichnungField = value;
                    this.RaisePropertyChanged("Bezeichnung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Grundflaeche {
            get {
                return this.GrundflaecheField;
            }
            set {
                if ((this.GrundflaecheField.Equals(value) != true)) {
                    this.GrundflaecheField = value;
                    this.RaisePropertyChanged("Grundflaeche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronisationLib.SynchronisationService.Attachements> HauspaketAttachements {
            get {
                return this.HauspaketAttachementsField;
            }
            set {
                if ((object.ReferenceEquals(this.HauspaketAttachementsField, value) != true)) {
                    this.HauspaketAttachementsField = value;
                    this.RaisePropertyChanged("HauspaketAttachements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronisationLib.SynchronisationService.HauspaketAttributZuord> HauspaketAttributZuordnungen {
            get {
                return this.HauspaketAttributZuordnungenField;
            }
            set {
                if ((object.ReferenceEquals(this.HauspaketAttributZuordnungenField, value) != true)) {
                    this.HauspaketAttributZuordnungenField = value;
                    this.RaisePropertyChanged("HauspaketAttributZuordnungen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HauspaketId {
            get {
                return this.HauspaketIdField;
            }
            set {
                if ((this.HauspaketIdField.Equals(value) != true)) {
                    this.HauspaketIdField = value;
                    this.RaisePropertyChanged("HauspaketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HerstellerId {
            get {
                return this.HerstellerIdField;
            }
            set {
                if ((this.HerstellerIdField.Equals(value) != true)) {
                    this.HerstellerIdField = value;
                    this.RaisePropertyChanged("HerstellerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Preis {
            get {
                return this.PreisField;
            }
            set {
                if ((this.PreisField.Equals(value) != true)) {
                    this.PreisField = value;
                    this.RaisePropertyChanged("Preis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Stockwerke {
            get {
                return this.StockwerkeField;
            }
            set {
                if ((this.StockwerkeField.Equals(value) != true)) {
                    this.StockwerkeField = value;
                    this.RaisePropertyChanged("Stockwerke");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Wohnflaeche {
            get {
                return this.WohnflaecheField;
            }
            set {
                if ((this.WohnflaecheField.Equals(value) != true)) {
                    this.WohnflaecheField = value;
                    this.RaisePropertyChanged("Wohnflaeche");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyncDataSet", Namespace="http://schemas.datacontract.org/2004/07/SynchronisationShared")]
    [System.SerializableAttribute()]
    public partial class SyncDataSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronisationLib.SynchronisationService.Attachements> AttachementsTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronisationLib.SynchronisationService.Berater> BeraterTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronisationLib.SynchronisationService.HauspaketAttributRegel> HauspaketAttributRegelTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronisationLib.SynchronisationService.HauspaketAttribut> HauspaketAttributTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronisationLib.SynchronisationService.HauspaketAttributWert> HauspaketAttributWertTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronisationLib.SynchronisationService.HauspaketAttributZuord> HauspaketAttributZuordTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronisationLib.SynchronisationService.Hauspaket> HauspaketTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<SynchronisationLib.SynchronisationService.Hersteller> HerstellerTableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronisationLib.SynchronisationService.Attachements> AttachementsTable {
            get {
                return this.AttachementsTableField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachementsTableField, value) != true)) {
                    this.AttachementsTableField = value;
                    this.RaisePropertyChanged("AttachementsTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronisationLib.SynchronisationService.Berater> BeraterTable {
            get {
                return this.BeraterTableField;
            }
            set {
                if ((object.ReferenceEquals(this.BeraterTableField, value) != true)) {
                    this.BeraterTableField = value;
                    this.RaisePropertyChanged("BeraterTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronisationLib.SynchronisationService.HauspaketAttributRegel> HauspaketAttributRegelTable {
            get {
                return this.HauspaketAttributRegelTableField;
            }
            set {
                if ((object.ReferenceEquals(this.HauspaketAttributRegelTableField, value) != true)) {
                    this.HauspaketAttributRegelTableField = value;
                    this.RaisePropertyChanged("HauspaketAttributRegelTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronisationLib.SynchronisationService.HauspaketAttribut> HauspaketAttributTable {
            get {
                return this.HauspaketAttributTableField;
            }
            set {
                if ((object.ReferenceEquals(this.HauspaketAttributTableField, value) != true)) {
                    this.HauspaketAttributTableField = value;
                    this.RaisePropertyChanged("HauspaketAttributTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronisationLib.SynchronisationService.HauspaketAttributWert> HauspaketAttributWertTable {
            get {
                return this.HauspaketAttributWertTableField;
            }
            set {
                if ((object.ReferenceEquals(this.HauspaketAttributWertTableField, value) != true)) {
                    this.HauspaketAttributWertTableField = value;
                    this.RaisePropertyChanged("HauspaketAttributWertTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronisationLib.SynchronisationService.HauspaketAttributZuord> HauspaketAttributZuordTable {
            get {
                return this.HauspaketAttributZuordTableField;
            }
            set {
                if ((object.ReferenceEquals(this.HauspaketAttributZuordTableField, value) != true)) {
                    this.HauspaketAttributZuordTableField = value;
                    this.RaisePropertyChanged("HauspaketAttributZuordTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronisationLib.SynchronisationService.Hauspaket> HauspaketTable {
            get {
                return this.HauspaketTableField;
            }
            set {
                if ((object.ReferenceEquals(this.HauspaketTableField, value) != true)) {
                    this.HauspaketTableField = value;
                    this.RaisePropertyChanged("HauspaketTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<SynchronisationLib.SynchronisationService.Hersteller> HerstellerTable {
            get {
                return this.HerstellerTableField;
            }
            set {
                if ((object.ReferenceEquals(this.HerstellerTableField, value) != true)) {
                    this.HerstellerTableField = value;
                    this.RaisePropertyChanged("HerstellerTable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SynchronisationService.ISynchronisationWCF")]
    public interface ISynchronisationWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronisationWCF/Ping", ReplyAction="http://tempuri.org/ISynchronisationWCF/PingResponse")]
        int Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronisationWCF/Ping", ReplyAction="http://tempuri.org/ISynchronisationWCF/PingResponse")]
        System.Threading.Tasks.Task<int> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronisationWCF/SaveHauspaket", ReplyAction="http://tempuri.org/ISynchronisationWCF/SaveHauspaketResponse")]
        int SaveHauspaket(SynchronisationLib.SynchronisationService.HauspaketDTO hauspaket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronisationWCF/SaveHauspaket", ReplyAction="http://tempuri.org/ISynchronisationWCF/SaveHauspaketResponse")]
        System.Threading.Tasks.Task<int> SaveHauspaketAsync(SynchronisationLib.SynchronisationService.HauspaketDTO hauspaket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronisationWCF/Synchronize", ReplyAction="http://tempuri.org/ISynchronisationWCF/SynchronizeResponse")]
        SynchronisationLib.SynchronisationService.SyncDataSet Synchronize(string type, string lastSync);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISynchronisationWCF/Synchronize", ReplyAction="http://tempuri.org/ISynchronisationWCF/SynchronizeResponse")]
        System.Threading.Tasks.Task<SynchronisationLib.SynchronisationService.SyncDataSet> SynchronizeAsync(string type, string lastSync);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISynchronisationWCFChannel : SynchronisationLib.SynchronisationService.ISynchronisationWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SynchronisationWCFClient : System.ServiceModel.ClientBase<SynchronisationLib.SynchronisationService.ISynchronisationWCF>, SynchronisationLib.SynchronisationService.ISynchronisationWCF {
        
        public SynchronisationWCFClient() {
        }
        
        public SynchronisationWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SynchronisationWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynchronisationWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SynchronisationWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<int> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public int SaveHauspaket(SynchronisationLib.SynchronisationService.HauspaketDTO hauspaket) {
            return base.Channel.SaveHauspaket(hauspaket);
        }
        
        public System.Threading.Tasks.Task<int> SaveHauspaketAsync(SynchronisationLib.SynchronisationService.HauspaketDTO hauspaket) {
            return base.Channel.SaveHauspaketAsync(hauspaket);
        }
        
        public SynchronisationLib.SynchronisationService.SyncDataSet Synchronize(string type, string lastSync) {
            return base.Channel.Synchronize(type, lastSync);
        }
        
        public System.Threading.Tasks.Task<SynchronisationLib.SynchronisationService.SyncDataSet> SynchronizeAsync(string type, string lastSync) {
            return base.Channel.SynchronizeAsync(type, lastSync);
        }
    }
}
